services:
  # Database Layer
  database:
    image: postgres:16-alpine
    container_name: storeforge-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: martin321! # Later, use a secret manager
      POSTGRES_DB: storeforge
    ports:
      - "5436:5432"
    volumes:
      - database_data:/var/lib/postgresql/data # Persists data even if container is deleted
    networks:
      - storeforge-net

  # ------ SERVICES LAYER ---------
  user-svc:
    build:
      context: .
      dockerfile: usermanagement/Dockerfile
    container_name: user-svc
    depends_on:
      - database
    ports:
      - "50051:50051"
    environment:
      # Use the container name 'user-db' as the hostname
      - DATABASE_URL=postgres://postgres:martin321!@database:5432/storeforge?sslmode=disable
      - GRPC_PORT=50051
      # This path must match the 'destination' in the volumes section below
      - JWT_PRIVATE_KEY_PATH=/etc/storeforge/certs/jwt_private.pem
    volumes:
      # FORMAT: [Host Path] : [Container Path] : [Permissions]
      - ./certs/jwt_private.pem:/etc/storeforge/certs/jwt_private.pem:ro
    networks:
      - storeforge-net

  tenant-svc:
    build:
      context: .
      dockerfile: tenantmanagement/Dockerfile
    container_name: tenant-svc
    depends_on:
      - database
      - user-svc
    ports:
      - "50052:50052"
    environment:
      # Use the container name 'user-db' as the hostname
      - DATABASE_URL=postgres://postgres:martin321!@database:5432/storeforge?sslmode=disable
      - GRPC_PORT=50052
    networks:
      - storeforge-net

  product-svc:
    build:
      context: .
      dockerfile: productmanagement/Dockerfile
    container_name: product-svc
    depends_on:
      - database
      - tenant-svc
    ports:
      - "50053:50053"
    environment:
      # Use the container name 'user-db' as the hostname
      - DATABASE_URL=postgres://postgres:martin321!@database:5432/storeforge?sslmode=disable
      - GRPC_PORT=50053
    networks:
      - storeforge-net

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: gateway-svc
    ports:
      - "9095:9095"
    environment:
      - JWT_PUBLIC_KEY_PATH=/etc/storeforge/certs/jwt_public.pem
      # --- Service Discovery (Hosts) ---
      # These must match the top-level service keys in this YAML file
      - USER_SVC_HOST=user-svc
      - TENANT_SVC_HOST=tenant-svc
      # - PRODUCT_SVC_HOST=product-svc

      # --- Service Ports ---
      - USER_SVC_GRPC_PORT=50051
      - TENANT_SVC_GRPC_PORT=50052
      - PRODUCT_SVC_GRPC_PORT=50053

      # --- Gateway Settings ---
      - GATEWAY_PORT=9095
      - GIN_MODE=debug # Switch to 'release' for production
    volumes:
      - ./certs/jwt_public.pem:/etc/storeforge/certs/jwt_public.pem:ro
    networks:
      - storeforge-net

networks:
  storeforge-net:
    driver: bridge

volumes:
  database_data:
