// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: tenantmanagement/theme/v1/theme.proto

package themev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ThemeService_GetThemeById_FullMethodName = "/theme.v1.ThemeService/GetThemeById"
)

// ThemeServiceClient is the client API for ThemeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ThemeService, theme_service handls theme related operations such as theme creation, retrieval, deletion and updates.
type ThemeServiceClient interface {
	GetThemeById(ctx context.Context, in *GetThemeByIdRequest, opts ...grpc.CallOption) (*GetThemeByIdResponse, error)
}

type themeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewThemeServiceClient(cc grpc.ClientConnInterface) ThemeServiceClient {
	return &themeServiceClient{cc}
}

func (c *themeServiceClient) GetThemeById(ctx context.Context, in *GetThemeByIdRequest, opts ...grpc.CallOption) (*GetThemeByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetThemeByIdResponse)
	err := c.cc.Invoke(ctx, ThemeService_GetThemeById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThemeServiceServer is the server API for ThemeService service.
// All implementations must embed UnimplementedThemeServiceServer
// for forward compatibility.
//
// ThemeService, theme_service handls theme related operations such as theme creation, retrieval, deletion and updates.
type ThemeServiceServer interface {
	GetThemeById(context.Context, *GetThemeByIdRequest) (*GetThemeByIdResponse, error)
	mustEmbedUnimplementedThemeServiceServer()
}

// UnimplementedThemeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedThemeServiceServer struct{}

func (UnimplementedThemeServiceServer) GetThemeById(context.Context, *GetThemeByIdRequest) (*GetThemeByIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetThemeById not implemented")
}
func (UnimplementedThemeServiceServer) mustEmbedUnimplementedThemeServiceServer() {}
func (UnimplementedThemeServiceServer) testEmbeddedByValue()                      {}

// UnsafeThemeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThemeServiceServer will
// result in compilation errors.
type UnsafeThemeServiceServer interface {
	mustEmbedUnimplementedThemeServiceServer()
}

func RegisterThemeServiceServer(s grpc.ServiceRegistrar, srv ThemeServiceServer) {
	// If the following call panics, it indicates UnimplementedThemeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ThemeService_ServiceDesc, srv)
}

func _ThemeService_GetThemeById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThemeByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThemeServiceServer).GetThemeById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThemeService_GetThemeById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThemeServiceServer).GetThemeById(ctx, req.(*GetThemeByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ThemeService_ServiceDesc is the grpc.ServiceDesc for ThemeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ThemeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "theme.v1.ThemeService",
	HandlerType: (*ThemeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetThemeById",
			Handler:    _ThemeService_GetThemeById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tenantmanagement/theme/v1/theme.proto",
}
