// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: tenantmanagement/theme/v1/theme.proto

package themev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Theme struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ThemeConfig   *structpb.Struct       `protobuf:"bytes,4,opt,name=theme_config,json=themeConfig,proto3" json:"theme_config,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Theme) Reset() {
	*x = Theme{}
	mi := &file_tenantmanagement_theme_v1_theme_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Theme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Theme) ProtoMessage() {}

func (x *Theme) ProtoReflect() protoreflect.Message {
	mi := &file_tenantmanagement_theme_v1_theme_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Theme.ProtoReflect.Descriptor instead.
func (*Theme) Descriptor() ([]byte, []int) {
	return file_tenantmanagement_theme_v1_theme_proto_rawDescGZIP(), []int{0}
}

func (x *Theme) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Theme) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Theme) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Theme) GetThemeConfig() *structpb.Struct {
	if x != nil {
		return x.ThemeConfig
	}
	return nil
}

func (x *Theme) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Theme) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetThemeByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThemeByIdRequest) Reset() {
	*x = GetThemeByIdRequest{}
	mi := &file_tenantmanagement_theme_v1_theme_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThemeByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThemeByIdRequest) ProtoMessage() {}

func (x *GetThemeByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenantmanagement_theme_v1_theme_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThemeByIdRequest.ProtoReflect.Descriptor instead.
func (*GetThemeByIdRequest) Descriptor() ([]byte, []int) {
	return file_tenantmanagement_theme_v1_theme_proto_rawDescGZIP(), []int{1}
}

func (x *GetThemeByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetThemeByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Theme         *Theme                 `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThemeByIdResponse) Reset() {
	*x = GetThemeByIdResponse{}
	mi := &file_tenantmanagement_theme_v1_theme_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThemeByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThemeByIdResponse) ProtoMessage() {}

func (x *GetThemeByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenantmanagement_theme_v1_theme_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThemeByIdResponse.ProtoReflect.Descriptor instead.
func (*GetThemeByIdResponse) Descriptor() ([]byte, []int) {
	return file_tenantmanagement_theme_v1_theme_proto_rawDescGZIP(), []int{2}
}

func (x *GetThemeByIdResponse) GetTheme() *Theme {
	if x != nil {
		return x.Theme
	}
	return nil
}

var File_tenantmanagement_theme_v1_theme_proto protoreflect.FileDescriptor

const file_tenantmanagement_theme_v1_theme_proto_rawDesc = "" +
	"\n" +
	"%tenantmanagement/theme/v1/theme.proto\x12\btheme.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xe1\x01\n" +
	"\x05Theme\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12:\n" +
	"\ftheme_config\x18\x04 \x01(\v2\x17.google.protobuf.StructR\vthemeConfig\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"%\n" +
	"\x13GetThemeByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x14GetThemeByIdResponse\x12%\n" +
	"\x05theme\x18\x01 \x01(\v2\x0f.theme.v1.ThemeR\x05theme2]\n" +
	"\fThemeService\x12M\n" +
	"\fGetThemeById\x12\x1d.theme.v1.GetThemeByIdRequest\x1a\x1e.theme.v1.GetThemeByIdResponseBRZPgithub.com/MartinMurithi/storeforge/api/protos/tenantmanagement/theme/v1;themev1b\x06proto3"

var (
	file_tenantmanagement_theme_v1_theme_proto_rawDescOnce sync.Once
	file_tenantmanagement_theme_v1_theme_proto_rawDescData []byte
)

func file_tenantmanagement_theme_v1_theme_proto_rawDescGZIP() []byte {
	file_tenantmanagement_theme_v1_theme_proto_rawDescOnce.Do(func() {
		file_tenantmanagement_theme_v1_theme_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tenantmanagement_theme_v1_theme_proto_rawDesc), len(file_tenantmanagement_theme_v1_theme_proto_rawDesc)))
	})
	return file_tenantmanagement_theme_v1_theme_proto_rawDescData
}

var file_tenantmanagement_theme_v1_theme_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tenantmanagement_theme_v1_theme_proto_goTypes = []any{
	(*Theme)(nil),                 // 0: theme.v1.Theme
	(*GetThemeByIdRequest)(nil),   // 1: theme.v1.GetThemeByIdRequest
	(*GetThemeByIdResponse)(nil),  // 2: theme.v1.GetThemeByIdResponse
	(*structpb.Struct)(nil),       // 3: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_tenantmanagement_theme_v1_theme_proto_depIdxs = []int32{
	3, // 0: theme.v1.Theme.theme_config:type_name -> google.protobuf.Struct
	4, // 1: theme.v1.Theme.created_at:type_name -> google.protobuf.Timestamp
	0, // 2: theme.v1.GetThemeByIdResponse.theme:type_name -> theme.v1.Theme
	1, // 3: theme.v1.ThemeService.GetThemeById:input_type -> theme.v1.GetThemeByIdRequest
	2, // 4: theme.v1.ThemeService.GetThemeById:output_type -> theme.v1.GetThemeByIdResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_tenantmanagement_theme_v1_theme_proto_init() }
func file_tenantmanagement_theme_v1_theme_proto_init() {
	if File_tenantmanagement_theme_v1_theme_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tenantmanagement_theme_v1_theme_proto_rawDesc), len(file_tenantmanagement_theme_v1_theme_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tenantmanagement_theme_v1_theme_proto_goTypes,
		DependencyIndexes: file_tenantmanagement_theme_v1_theme_proto_depIdxs,
		MessageInfos:      file_tenantmanagement_theme_v1_theme_proto_msgTypes,
	}.Build()
	File_tenantmanagement_theme_v1_theme_proto = out.File
	file_tenantmanagement_theme_v1_theme_proto_goTypes = nil
	file_tenantmanagement_theme_v1_theme_proto_depIdxs = nil
}
