// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: tenantmanagement/tenant/v1/tenant.proto

package tenantv1

import (
	v1 "github.com/MartinMurithi/storeforge/api/protos/tenantmanagement/theme/v1"
	v11 "github.com/MartinMurithi/storeforge/api/protos/usermanagement/auth/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tenant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StoreName     string                 `protobuf:"bytes,2,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	SubDomain     string                 `protobuf:"bytes,4,opt,name=sub_domain,json=subDomain,proto3" json:"sub_domain,omitempty"`
	Domain        string                 `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty"`
	BusinessType  string                 `protobuf:"bytes,6,opt,name=business_type,json=businessType,proto3" json:"business_type,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_tenantmanagement_tenant_v1_tenant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_tenantmanagement_tenant_v1_tenant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_tenantmanagement_tenant_v1_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *Tenant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tenant) GetStoreName() string {
	if x != nil {
		return x.StoreName
	}
	return ""
}

func (x *Tenant) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Tenant) GetSubDomain() string {
	if x != nil {
		return x.SubDomain
	}
	return ""
}

func (x *Tenant) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Tenant) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

func (x *Tenant) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Tenant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Tenant) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Tenant) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type TenantSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ThemeId       string                 `protobuf:"bytes,2,opt,name=theme_id,json=themeId,proto3" json:"theme_id,omitempty"`
	ThemeConfig   *structpb.Struct       `protobuf:"bytes,3,opt,name=theme_config,json=themeConfig,proto3" json:"theme_config,omitempty"`
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Updated       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantSettings) Reset() {
	*x = TenantSettings{}
	mi := &file_tenantmanagement_tenant_v1_tenant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantSettings) ProtoMessage() {}

func (x *TenantSettings) ProtoReflect() protoreflect.Message {
	mi := &file_tenantmanagement_tenant_v1_tenant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantSettings.ProtoReflect.Descriptor instead.
func (*TenantSettings) Descriptor() ([]byte, []int) {
	return file_tenantmanagement_tenant_v1_tenant_proto_rawDescGZIP(), []int{1}
}

func (x *TenantSettings) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantSettings) GetThemeId() string {
	if x != nil {
		return x.ThemeId
	}
	return ""
}

func (x *TenantSettings) GetThemeConfig() *structpb.Struct {
	if x != nil {
		return x.ThemeConfig
	}
	return nil
}

func (x *TenantSettings) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TenantSettings) GetUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.Updated
	}
	return nil
}

type CreateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreName     string                 `protobuf:"bytes,1,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	BusinessType  string                 `protobuf:"bytes,2,opt,name=business_type,json=businessType,proto3" json:"business_type,omitempty"`
	ThemeId       string                 `protobuf:"bytes,3,opt,name=theme_id,json=themeId,proto3" json:"theme_id,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantRequest) Reset() {
	*x = CreateTenantRequest{}
	mi := &file_tenantmanagement_tenant_v1_tenant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantRequest) ProtoMessage() {}

func (x *CreateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenantmanagement_tenant_v1_tenant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantRequest) Descriptor() ([]byte, []int) {
	return file_tenantmanagement_tenant_v1_tenant_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTenantRequest) GetStoreName() string {
	if x != nil {
		return x.StoreName
	}
	return ""
}

func (x *CreateTenantRequest) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

func (x *CreateTenantRequest) GetThemeId() string {
	if x != nil {
		return x.ThemeId
	}
	return ""
}

func (x *CreateTenantRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *Tenant                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Theme         *v1.Theme              `protobuf:"bytes,2,opt,name=theme,proto3" json:"theme,omitempty"`
	Settings      *TenantSettings        `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"`
	Token         *v11.Token             `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantResponse) Reset() {
	*x = CreateTenantResponse{}
	mi := &file_tenantmanagement_tenant_v1_tenant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantResponse) ProtoMessage() {}

func (x *CreateTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenantmanagement_tenant_v1_tenant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantResponse.ProtoReflect.Descriptor instead.
func (*CreateTenantResponse) Descriptor() ([]byte, []int) {
	return file_tenantmanagement_tenant_v1_tenant_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTenantResponse) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

func (x *CreateTenantResponse) GetTheme() *v1.Theme {
	if x != nil {
		return x.Theme
	}
	return nil
}

func (x *CreateTenantResponse) GetSettings() *TenantSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *CreateTenantResponse) GetToken() *v11.Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type GetTenantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*GetTenantRequest_Id
	//	*GetTenantRequest_Slug
	Identifier    isGetTenantRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantRequest) Reset() {
	*x = GetTenantRequest{}
	mi := &file_tenantmanagement_tenant_v1_tenant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantRequest) ProtoMessage() {}

func (x *GetTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenantmanagement_tenant_v1_tenant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantRequest.ProtoReflect.Descriptor instead.
func (*GetTenantRequest) Descriptor() ([]byte, []int) {
	return file_tenantmanagement_tenant_v1_tenant_proto_rawDescGZIP(), []int{4}
}

func (x *GetTenantRequest) GetIdentifier() isGetTenantRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetTenantRequest) GetId() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetTenantRequest_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *GetTenantRequest) GetSlug() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetTenantRequest_Slug); ok {
			return x.Slug
		}
	}
	return ""
}

type isGetTenantRequest_Identifier interface {
	isGetTenantRequest_Identifier()
}

type GetTenantRequest_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type GetTenantRequest_Slug struct {
	Slug string `protobuf:"bytes,2,opt,name=slug,proto3,oneof"`
}

func (*GetTenantRequest_Id) isGetTenantRequest_Identifier() {}

func (*GetTenantRequest_Slug) isGetTenantRequest_Identifier() {}

type GetTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *Tenant                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantResponse) Reset() {
	*x = GetTenantResponse{}
	mi := &file_tenantmanagement_tenant_v1_tenant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantResponse) ProtoMessage() {}

func (x *GetTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenantmanagement_tenant_v1_tenant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantResponse.ProtoReflect.Descriptor instead.
func (*GetTenantResponse) Descriptor() ([]byte, []int) {
	return file_tenantmanagement_tenant_v1_tenant_proto_rawDescGZIP(), []int{5}
}

func (x *GetTenantResponse) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

var File_tenantmanagement_tenant_v1_tenant_proto protoreflect.FileDescriptor

const file_tenantmanagement_tenant_v1_tenant_proto_rawDesc = "" +
	"\n" +
	"'tenantmanagement/tenant/v1/tenant.proto\x12\ttenant.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a%tenantmanagement/theme/v1/theme.proto\x1a!usermanagement/auth/v1/auth.proto\"\xf0\x02\n" +
	"\x06Tenant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"store_name\x18\x02 \x01(\tR\tstoreName\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x1d\n" +
	"\n" +
	"sub_domain\x18\x04 \x01(\tR\tsubDomain\x12\x16\n" +
	"\x06domain\x18\x05 \x01(\tR\x06domain\x12#\n" +
	"\rbusiness_type\x18\x06 \x01(\tR\fbusinessType\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\xd4\x01\n" +
	"\x0eTenantSettings\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\btheme_id\x18\x02 \x01(\tR\athemeId\x12:\n" +
	"\ftheme_config\x18\x03 \x01(\v2\x17.google.protobuf.StructR\vthemeConfig\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x124\n" +
	"\aupdated\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aupdated\"\x8d\x01\n" +
	"\x13CreateTenantRequest\x12\x1d\n" +
	"\n" +
	"store_name\x18\x01 \x01(\tR\tstoreName\x12#\n" +
	"\rbusiness_type\x18\x02 \x01(\tR\fbusinessType\x12\x19\n" +
	"\btheme_id\x18\x03 \x01(\tR\athemeId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"\xc9\x01\n" +
	"\x14CreateTenantResponse\x12)\n" +
	"\x06tenant\x18\x01 \x01(\v2\x11.tenant.v1.TenantR\x06tenant\x12%\n" +
	"\x05theme\x18\x02 \x01(\v2\x0f.theme.v1.ThemeR\x05theme\x125\n" +
	"\bsettings\x18\x03 \x01(\v2\x19.tenant.v1.TenantSettingsR\bsettings\x12(\n" +
	"\x05token\x18\x04 \x01(\v2\x12.api.auth.v1.TokenR\x05token\"H\n" +
	"\x10GetTenantRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x12\x14\n" +
	"\x04slug\x18\x02 \x01(\tH\x00R\x04slugB\f\n" +
	"\n" +
	"identifier\">\n" +
	"\x11GetTenantResponse\x12)\n" +
	"\x06tenant\x18\x01 \x01(\v2\x11.tenant.v1.TenantR\x06tenant2\xa8\x01\n" +
	"\rTenantService\x12O\n" +
	"\fCreateTenant\x12\x1e.tenant.v1.CreateTenantRequest\x1a\x1f.tenant.v1.CreateTenantResponse\x12F\n" +
	"\tGetTenant\x12\x1b.tenant.v1.GetTenantRequest\x1a\x1c.tenant.v1.GetTenantResponseBTZRgithub.com/MartinMurithi/storeforge/api/protos/tenantmanagement/tenant/v1;tenantv1b\x06proto3"

var (
	file_tenantmanagement_tenant_v1_tenant_proto_rawDescOnce sync.Once
	file_tenantmanagement_tenant_v1_tenant_proto_rawDescData []byte
)

func file_tenantmanagement_tenant_v1_tenant_proto_rawDescGZIP() []byte {
	file_tenantmanagement_tenant_v1_tenant_proto_rawDescOnce.Do(func() {
		file_tenantmanagement_tenant_v1_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tenantmanagement_tenant_v1_tenant_proto_rawDesc), len(file_tenantmanagement_tenant_v1_tenant_proto_rawDesc)))
	})
	return file_tenantmanagement_tenant_v1_tenant_proto_rawDescData
}

var file_tenantmanagement_tenant_v1_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tenantmanagement_tenant_v1_tenant_proto_goTypes = []any{
	(*Tenant)(nil),                // 0: tenant.v1.Tenant
	(*TenantSettings)(nil),        // 1: tenant.v1.TenantSettings
	(*CreateTenantRequest)(nil),   // 2: tenant.v1.CreateTenantRequest
	(*CreateTenantResponse)(nil),  // 3: tenant.v1.CreateTenantResponse
	(*GetTenantRequest)(nil),      // 4: tenant.v1.GetTenantRequest
	(*GetTenantResponse)(nil),     // 5: tenant.v1.GetTenantResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 7: google.protobuf.Struct
	(*v1.Theme)(nil),              // 8: theme.v1.Theme
	(*v11.Token)(nil),             // 9: api.auth.v1.Token
}
var file_tenantmanagement_tenant_v1_tenant_proto_depIdxs = []int32{
	6,  // 0: tenant.v1.Tenant.created_at:type_name -> google.protobuf.Timestamp
	6,  // 1: tenant.v1.Tenant.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 2: tenant.v1.Tenant.deleted_at:type_name -> google.protobuf.Timestamp
	7,  // 3: tenant.v1.TenantSettings.theme_config:type_name -> google.protobuf.Struct
	6,  // 4: tenant.v1.TenantSettings.updated:type_name -> google.protobuf.Timestamp
	0,  // 5: tenant.v1.CreateTenantResponse.tenant:type_name -> tenant.v1.Tenant
	8,  // 6: tenant.v1.CreateTenantResponse.theme:type_name -> theme.v1.Theme
	1,  // 7: tenant.v1.CreateTenantResponse.settings:type_name -> tenant.v1.TenantSettings
	9,  // 8: tenant.v1.CreateTenantResponse.token:type_name -> api.auth.v1.Token
	0,  // 9: tenant.v1.GetTenantResponse.tenant:type_name -> tenant.v1.Tenant
	2,  // 10: tenant.v1.TenantService.CreateTenant:input_type -> tenant.v1.CreateTenantRequest
	4,  // 11: tenant.v1.TenantService.GetTenant:input_type -> tenant.v1.GetTenantRequest
	3,  // 12: tenant.v1.TenantService.CreateTenant:output_type -> tenant.v1.CreateTenantResponse
	5,  // 13: tenant.v1.TenantService.GetTenant:output_type -> tenant.v1.GetTenantResponse
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_tenantmanagement_tenant_v1_tenant_proto_init() }
func file_tenantmanagement_tenant_v1_tenant_proto_init() {
	if File_tenantmanagement_tenant_v1_tenant_proto != nil {
		return
	}
	file_tenantmanagement_tenant_v1_tenant_proto_msgTypes[4].OneofWrappers = []any{
		(*GetTenantRequest_Id)(nil),
		(*GetTenantRequest_Slug)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tenantmanagement_tenant_v1_tenant_proto_rawDesc), len(file_tenantmanagement_tenant_v1_tenant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tenantmanagement_tenant_v1_tenant_proto_goTypes,
		DependencyIndexes: file_tenantmanagement_tenant_v1_tenant_proto_depIdxs,
		MessageInfos:      file_tenantmanagement_tenant_v1_tenant_proto_msgTypes,
	}.Build()
	File_tenantmanagement_tenant_v1_tenant_proto = out.File
	file_tenantmanagement_tenant_v1_tenant_proto_goTypes = nil
	file_tenantmanagement_tenant_v1_tenant_proto_depIdxs = nil
}
