// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: usermanagement/membership/v1/membership.proto

package membershipv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LinkUserToTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // 'owner', 'admin', 'editor', 'viewer'.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkUserToTenantRequest) Reset() {
	*x = LinkUserToTenantRequest{}
	mi := &file_usermanagement_membership_v1_membership_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkUserToTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkUserToTenantRequest) ProtoMessage() {}

func (x *LinkUserToTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usermanagement_membership_v1_membership_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkUserToTenantRequest.ProtoReflect.Descriptor instead.
func (*LinkUserToTenantRequest) Descriptor() ([]byte, []int) {
	return file_usermanagement_membership_v1_membership_proto_rawDescGZIP(), []int{0}
}

func (x *LinkUserToTenantRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LinkUserToTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *LinkUserToTenantRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type LinkUserToTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkUserToTenantResponse) Reset() {
	*x = LinkUserToTenantResponse{}
	mi := &file_usermanagement_membership_v1_membership_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkUserToTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkUserToTenantResponse) ProtoMessage() {}

func (x *LinkUserToTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usermanagement_membership_v1_membership_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkUserToTenantResponse.ProtoReflect.Descriptor instead.
func (*LinkUserToTenantResponse) Descriptor() ([]byte, []int) {
	return file_usermanagement_membership_v1_membership_proto_rawDescGZIP(), []int{1}
}

func (x *LinkUserToTenantResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LinkUserToTenantResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_usermanagement_membership_v1_membership_proto protoreflect.FileDescriptor

const file_usermanagement_membership_v1_membership_proto_rawDesc = "" +
	"\n" +
	"-usermanagement/membership/v1/membership.proto\x12\rmembership.v1\"c\n" +
	"\x17LinkUserToTenantRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"N\n" +
	"\x18LinkUserToTenantResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2x\n" +
	"\x11MembershipService\x12c\n" +
	"\x10LinkUserToTenant\x12&.membership.v1.LinkUserToTenantRequest\x1a'.membership.v1.LinkUserToTenantResponseBZZXgithub.com/MartinMurithi/storeforge/api/protos/usermanagement/membership/v1;membershipv1b\x06proto3"

var (
	file_usermanagement_membership_v1_membership_proto_rawDescOnce sync.Once
	file_usermanagement_membership_v1_membership_proto_rawDescData []byte
)

func file_usermanagement_membership_v1_membership_proto_rawDescGZIP() []byte {
	file_usermanagement_membership_v1_membership_proto_rawDescOnce.Do(func() {
		file_usermanagement_membership_v1_membership_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_usermanagement_membership_v1_membership_proto_rawDesc), len(file_usermanagement_membership_v1_membership_proto_rawDesc)))
	})
	return file_usermanagement_membership_v1_membership_proto_rawDescData
}

var file_usermanagement_membership_v1_membership_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_usermanagement_membership_v1_membership_proto_goTypes = []any{
	(*LinkUserToTenantRequest)(nil),  // 0: membership.v1.LinkUserToTenantRequest
	(*LinkUserToTenantResponse)(nil), // 1: membership.v1.LinkUserToTenantResponse
}
var file_usermanagement_membership_v1_membership_proto_depIdxs = []int32{
	0, // 0: membership.v1.MembershipService.LinkUserToTenant:input_type -> membership.v1.LinkUserToTenantRequest
	1, // 1: membership.v1.MembershipService.LinkUserToTenant:output_type -> membership.v1.LinkUserToTenantResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_usermanagement_membership_v1_membership_proto_init() }
func file_usermanagement_membership_v1_membership_proto_init() {
	if File_usermanagement_membership_v1_membership_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_usermanagement_membership_v1_membership_proto_rawDesc), len(file_usermanagement_membership_v1_membership_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_usermanagement_membership_v1_membership_proto_goTypes,
		DependencyIndexes: file_usermanagement_membership_v1_membership_proto_depIdxs,
		MessageInfos:      file_usermanagement_membership_v1_membership_proto_msgTypes,
	}.Build()
	File_usermanagement_membership_v1_membership_proto = out.File
	file_usermanagement_membership_v1_membership_proto_goTypes = nil
	file_usermanagement_membership_v1_membership_proto_depIdxs = nil
}
